package com.duduapps.mybanks.util

const val PREF_DEVICE_ID = "PrefDeviceId"
const val PREF_DEVICE_ID_OLD = "PrefIdentifier"
const val PREF_LOGGED = "PrefLogged"
const val PREF_FCM_TOKEN = "PrefFcmToken"
const val PREF_SHARE_LINK = "PrefStoreLink"
const val PREF_UPDATE_ON_SPLASH = "PrefUpdateOnSplash"
const val PREF_LAST_HOLDER = "PrefLastHolder"
const val PREF_LAST_DOCUMENT = "PrefLastDocument"
const val PREF_LAST_LEGAL_ACCOUNT = "PrefLastLegalAccount"
const val PREF_SHOW_ALERT_LOGIN = "PrefShowAlertLogin"

const val PREF_APP_NAME = "PrefAppName"
const val PREF_PLAN_VIDEO_DURATION = "PrefPlanVideoDuration"
const val PREF_PLAN_VIDEO_MILLIS = "PrefPlanVideoMillis"
const val PREF_NAME = "PrefName"
const val PREF_EMAIL = "PrefEmail"
const val PREF_COMMENTS = "PrefComments"

const val PREF_ADMOB_ID = "PrefAdMobId"
const val PREF_ADMOB_AD_MAIN_ID = "PrefAdMobAdMainId"
const val PREF_ADMOB_INTERSTITIAL_ID = "PrefAdMobInterstitialId"
const val PREF_ADMOB_REMOVE_ADS = "PrefAdMobRemoveAds"
const val PREF_ADMOB_OPEN_APP_ID = "PrefAdMobOpenAppId"
